name: CI

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
      - name: setup
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock')}}
      - name: install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: build
        run: npm build
      - name: test
        run: npm test
  
