name: CI

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
      - name: setup
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: build
        run: npm build
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and run tests
        run: npm test
  
