name: CI

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: setup
        run: npx playwright install-deps && npx playwright install-deps chromium && npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
  
